# version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - web
    # volumes:
    #   - ./srcs/backend/data:/app/data
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - web


networks:
  web:
    name: transcendence
