sequenceDiagram
    participant U as User
    participant FE as Frontend

    U->>FE: Click "Play Game" on Home Page

    alt Logged in
    else Not logged in
        FE->>U: Redirect to Register Page
        U->>FE: Submit register { username, email, password }
    end
    
    FE->>U: Redirect to user profile page with 'Play Game with AI' and 'Play Game with 'Human'
    U->>FE: Clicks 'Play Game with Human'
    
    FE->>U: Sets player 1 on the right with username displayed    
    FE->>U: Prompt second player to type username
    U->>FE: User types a username
    
    FE->>U: Prompts 'Ready' button for players
    U->>FE: Player clicks 'Ready'
    
    FE->>U: Game starts
    U->>FE: Player scores
    
    U->>FE: Player pauses game
    FE->>U: Paused screen

    U->>FE: Player unpauses game
    FE->>U: Game continues

    alt Game finishes
        U->>FE: Player scores (and reaches winning score)
        FE->>U: Game ended 
    else Game aborted
        U->>FE: User clicks 'Quit Match' button (or navigates to another page)
    end

