sequenceDiagram
    participant U as User
    participant FE as Frontend

    U->>FE: Logged-in player clicks "Play Tournament" on Home Page
    FE->>U: Prompt for number of players
    U->>FE: Input 4 players
    FE->>U: Prompt for guest username or login credentials for 2nd player
	U->>FE: Provides login credentials
	FE->>U: Prompt for guest username or login credentials for 3rd player
	U->>FE: Provides login credentials
	FE->>U: Prompt for guest username or login credentials for 4th player
	U->>FE: Provides guest username
    FE->>U: Show lineup of matches with 'Start Tournament' button
	U->>FE: Click 'Start Tournament'
	FE->>U: Show Match 1 Players with 'Ready' button
	U->>FE: Click 'Ready'
	FE->>U: Starts Game
	U<<->>FE: ...
	FE->>U: End of game with button for 'Next Match'
	U->>FE: Click 'Next Match'
	FE->>U: Show Match 2 Players with 'Ready' button
	U<<->>FE: ...
	FE->>U: End of game with button for 'Next Match'
	U->>FE: Click 'Next Match'
	FE->>U: Show Match 3 Players with 'Ready' button
	U<<->>FE: ...
	FE->>U: End of game with button for 'Show Results'
	U->>FE: Clicks 'Show Results'
	FE->>U: Shows Tournament Results (Winner, Bracket, Stats)
	FE->>U: Display 'Play Again'

	



