sequenceDiagram
    participant U as User
    participant FE as Frontend
    participant BE as Backend

    U->>FE: Logged-in player clicks "Play Tournament" on Home Page
    FE->>U: Prompt for number of players
    U->>FE: Input 4 players
	FE->>BE: POST /api/tournaments 
    BE->>FE: 201 Tournament created { id }

    %% Add player 2
    FE->>U: Prompt for guest username or login credentials for 2nd player
	U->>FE: Provides login credentials
	FE->>BE: POST /api/tournaments/:id/players { username, password }
	BE->>FE: 200 Player added
    
    %% Add player 3
	FE->>U: Prompt for guest username or login credentials for 3rd player
	U->>FE: Provides login credentials
	FE->>BE: POST /api/tournaments/:id/players { username, password }
	BE->>FE: 200 Player added
	
    %% Add player 4
	FE->>U: Prompt for guest username or login credentials for 4th player
	U->>FE: Provides guest username
	FE->>BE: POST /api/tournaments/:id/players { guestName }
	BE->>FE: 200 Player added
    
	FE->>U: Show lineup of matches with 'Start Tournament' button
	U->>FE: Click 'Start Tournament'
	FE->>BE: PATCH /api/tournaments/:id { status: "started" }
    BE->>FE: 200 Tournament started { matches with gameSessionIds for round 1}
	
    %% Match 1 
    FE->>BE: GET /api/tournaments/:id/next-match
	BE->>FE: 200 { matchIndex: 1, gameSessionId }
    FE->>U: Show Match 1 Players with 'Ready' button
    U->>FE: Click 'Ready'
	FE->>BE: PATCH /api/game-sessions/:id/status { status: "STARTED" }
	BE->>FE: 200 Game started
	U<<-->>FE: (Gameplay)

	%% Scoring & advancing
	U->>FE: Player scores (and reaches winning score)
    FE->>BE: PATCH /api/game-sessions/:id/players/:side/score
	BE->>FE: 200 (User's score incremented by 1) { gameStatus = FINISHED, winnerUserId }
	FE->>U: End of game with button for 'Next'

    %% Match 2
	U->>FE: Click 'Next'
	FE->>BE: GET /api/tournaments/:id/next-match
	BE->>FE: 200 { matchIndex: 2, gameSessionId }
	FE->>U: Show Match 2 Players with 'Ready' button
	U<<-->>FE: (Gameplay)
	FE->>U: End of game with button for 'Next'
	
	%% Match 3
	U->>FE: Click 'Next'
	FE->>BE: GET /api/tournaments/:id/next-match
	BE->>FE: 200 { matchIndex: 3, gameSessionId }
	FE->>U: Show Match 3 Players with 'Ready' button
	U<<-->>FE: (Gameplay)
	FE->>U: End of game with button for 'Next'
	
	%% Final match ends
	U->>FE: Clicks 'Next'
	FE->>BE: GET /api/tournaments/:id/next-match
	BE->>FE: 200 { nextMatch: null, status: "FINISHED", results }
	FE->>U: Shows Tournament Results (Winner, Bracket, Stats)
	FE->>U: Display 'Play Again'

	


